language: python
matrix:
  include:
    - name: "Python 2.7 on Linux"
      python: 2.7
    - name: "Python 2.6 on Linux"
      python: 2.6
    - name: "Python 2.5 on Linux"
      python: 2.5
install: pip install -ve .
script: which python &> /dev/null && PYTHON=python || PYTHON=python; $PYTHON --version; $PYTHON -c '__import__("guppy").hpy().test()'
