language: python
matrix:
  include:
    - name: "Python 2.7 on Linux"
      python: 2.7
script: which python &> /dev/null && PYTHON=python || PYTHON=python; $PYTHON --version; $PYTHON -c '__import__("guppy").hpy().test()'
